---
# maintains versions and can overwrite all.yml
sui:
  validator:
    version: 04dd28d5c5d92bff685ddfecb86f8acce18ce6df
    external_address: validator.sui.mainnet.encapsulate.xyz
  fullnode:
    version: 04dd28d5c5d92bff685ddfecb86f8acce18ce6df
  bridge:
    version: 04dd28d5c5d92bff685ddfecb86f8acce18ce6df
  dummy:
    version: 04dd28d5c5d92bff685ddfecb86f8acce18ce6df
    external_address: dummy.sui.mainnet.encapsulate.xyz
