---
# maintains versions and can overwrite all.yml
sui:
  validator:
    version: 6fa07e1fb8d148931e2ce90246dd1de244f0e024
    external_address: validator.sui.mainnet.encapsulate.xyz
  fullnode:
    version: 1073a8fbf6cfa0d4a4d2bf34b2494a212116089c
  bridge:
    version: 1073a8fbf6cfa0d4a4d2bf34b2494a212116089c
  dummy:
    version: 1073a8fbf6cfa0d4a4d2bf34b2494a212116089c
    external_address: dummy.sui.mainnet.encapsulate.xyz
