---
# maintains versions and can overwrite all.yml
sui:
  validator:
    version: 49d95e90e36ea0f2e20a74e23843ada90ce4a3bc
    external_address: validator.sui.mainnet.encapsulate.xyz
  fullnode:
    version: 49d95e90e36ea0f2e20a74e23843ada90ce4a3bc
  bridge:
    version: 49d95e90e36ea0f2e20a74e23843ada90ce4a3bc
  dummy:
    version: 49d95e90e36ea0f2e20a74e23843ada90ce4a3bc
    external_address: dummy.sui.mainnet.encapsulate.xyz
