---
# maintains versions and can overwrite all.yml
sui:
  validator:
    version: 2c49405cfa325304696aa8fd936bf62c2c515f9a
    external_address: validator.sui.mainnet.encapsulate.xyz
  fullnode:
    version: 2c49405cfa325304696aa8fd936bf62c2c515f9a
  bridge:
    version: 2c49405cfa325304696aa8fd936bf62c2c515f9a
  dummy:
    version: 2c49405cfa325304696aa8fd936bf62c2c515f9a
    external_address: dummy.sui.mainnet.encapsulate.xyz
