---
# maintains versions and can overwrite all.yml
sui:
  validator:
    version: a9a6825eaf6273cc819ee3bcf65fd4909f7624a9
    external_address: validator.sui.testnet.encapsulate.xyz
  fullnode:
    version: a9a6825eaf6273cc819ee3bcf65fd4909f7624a9
  bridge:
    version: a9a6825eaf6273cc819ee3bcf65fd4909f7624a9
  dummy:
    version: a9a6825eaf6273cc819ee3bcf65fd4909f7624a9
    external_address:
