---
# maintains versions and can overwrite all.yml
sui:
  validator:
    version: 5484a7e2b67cfc116cd235fa0b8e2b858058823b
    external_address: validator.sui.testnet.encapsulate.xyz
  fullnode:
    version: 5484a7e2b67cfc116cd235fa0b8e2b858058823b
  bridge:
    version: 5484a7e2b67cfc116cd235fa0b8e2b858058823b
  dummy:
    version: 5484a7e2b67cfc116cd235fa0b8e2b858058823b
    external_address:
