---
# maintains versions and can overwrite all.yml
sui:
  validator:
    version: 75515e79e182c37b135a9984c6c1f08a2c383736
    external_address: validator.sui.testnet.encapsulate.xyz
  fullnode:
    version: 75515e79e182c37b135a9984c6c1f08a2c383736
  bridge:
    version: 75515e79e182c37b135a9984c6c1f08a2c383736
  dummy:
    version: 75515e79e182c37b135a9984c6c1f08a2c383736
    external_address:
