---
# maintains versions and can overwrite all.yml
sui:
  validator:
    version: bac3f508b83be5812fd937c84f7d5395c020b219
    external_address: validator.sui.testnet.encapsulate.xyz
  fullnode:
    version: bac3f508b83be5812fd937c84f7d5395c020b219
  bridge:
    version: bac3f508b83be5812fd937c84f7d5395c020b219
  dummy:
    version: bac3f508b83be5812fd937c84f7d5395c020b219
    external_address:
