---
# maintains versions and can overwrite all.yml
sui:
  validator:
    version: 833c3bbde1f06c35dec7e6954d168fc8b527880f
    external_address: validator.sui.testnet.encapsulate.xyz
  fullnode:
    version: 833c3bbde1f06c35dec7e6954d168fc8b527880f
  bridge:
    version: 833c3bbde1f06c35dec7e6954d168fc8b527880f
  dummy:
    version: 833c3bbde1f06c35dec7e6954d168fc8b527880f
    external_address:
