---
# maintains versions and can overwrite all.yml
sui:
  validator:
    version: 6c229fe6c04fb21ec98751c798e57e9a00e028e2
    external_address: validator.sui.testnet.encapsulate.xyz
  fullnode:
    version: 6c229fe6c04fb21ec98751c798e57e9a00e028e2
  bridge:
    version: 7980604377ead9590c7797cf524b015a6ec4569b
  dummy:
    version: 6c229fe6c04fb21ec98751c798e57e9a00e028e2
    external_address:
