---
# maintains versions and can overwrite all.yml
sui:
  validator:
    version: 0def7a08f11a2ec992e11123c5f5ac5e0279e0a0
    external_address: validator.sui.testnet.encapsulate.xyz
  fullnode:
    version: 0def7a08f11a2ec992e11123c5f5ac5e0279e0a0
  bridge:
    version: 0def7a08f11a2ec992e11123c5f5ac5e0279e0a0
  dummy:
    version: 0def7a08f11a2ec992e11123c5f5ac5e0279e0a0
    external_address:
